/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SdfsdfsdfService } from "../sdfsdfsdf.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SdfsdfsdfCreateInput } from "./SdfsdfsdfCreateInput";
import { SdfsdfsdfWhereInput } from "./SdfsdfsdfWhereInput";
import { SdfsdfsdfWhereUniqueInput } from "./SdfsdfsdfWhereUniqueInput";
import { SdfsdfsdfFindManyArgs } from "./SdfsdfsdfFindManyArgs";
import { SdfsdfsdfUpdateInput } from "./SdfsdfsdfUpdateInput";
import { Sdfsdfsdf } from "./Sdfsdfsdf";
import { SdfFindManyArgs } from "../../sdf/base/SdfFindManyArgs";
import { Sdf } from "../../sdf/base/Sdf";
import { SdfWhereUniqueInput } from "../../sdf/base/SdfWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SdfsdfsdfControllerBase {
  constructor(
    protected readonly service: SdfsdfsdfService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Sdfsdfsdf })
  @nestAccessControl.UseRoles({
    resource: "Sdfsdfsdf",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: SdfsdfsdfCreateInput): Promise<Sdfsdfsdf> {
    return await this.service.create({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Sdfsdfsdf] })
  @ApiNestedQuery(SdfsdfsdfFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Sdfsdfsdf",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Sdfsdfsdf[]> {
    const args = plainToClass(SdfsdfsdfFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Sdfsdfsdf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sdfsdfsdf",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: SdfsdfsdfWhereUniqueInput
  ): Promise<Sdfsdfsdf | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Sdfsdfsdf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sdfsdfsdf",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: SdfsdfsdfWhereUniqueInput,
    @common.Body() data: SdfsdfsdfUpdateInput
  ): Promise<Sdfsdfsdf | null> {
    try {
      return await this.service.update({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Sdfsdfsdf })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Sdfsdfsdf",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: SdfsdfsdfWhereUniqueInput
  ): Promise<Sdfsdfsdf | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/sdfs")
  @ApiNestedQuery(SdfFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Sdf",
    action: "read",
    possession: "any",
  })
  async findManySdfs(
    @common.Req() request: Request,
    @common.Param() params: SdfsdfsdfWhereUniqueInput
  ): Promise<Sdf[]> {
    const query = plainToClass(SdfFindManyArgs, request.query);
    const results = await this.service.findSdfs(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        sdfsdfsdf: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/sdfs")
  @nestAccessControl.UseRoles({
    resource: "Sdfsdfsdf",
    action: "update",
    possession: "any",
  })
  async connectSdfs(
    @common.Param() params: SdfsdfsdfWhereUniqueInput,
    @common.Body() body: SdfWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sdfs: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/sdfs")
  @nestAccessControl.UseRoles({
    resource: "Sdfsdfsdf",
    action: "update",
    possession: "any",
  })
  async updateSdfs(
    @common.Param() params: SdfsdfsdfWhereUniqueInput,
    @common.Body() body: SdfWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sdfs: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/sdfs")
  @nestAccessControl.UseRoles({
    resource: "Sdfsdfsdf",
    action: "update",
    possession: "any",
  })
  async disconnectSdfs(
    @common.Param() params: SdfsdfsdfWhereUniqueInput,
    @common.Body() body: SdfWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      sdfs: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
